-- INDANE SALES MONITORING - Supabase common repository setup
-- Paste this once in Supabase SQL Editor and click Run.
-- This simple free setup creates one common portal data record and one audit table.

create table if not exists public.portal_state (
  id text primary key,
  data jsonb not null default '{}'::jsonb,
  updated_by text,
  updated_at timestamptz default now()
);

create table if not exists public.portal_audit_log (
  id bigint generated by default as identity primary key,
  user_id text,
  role text,
  action text,
  target text,
  details text,
  created_at timestamptz default now()
);

insert into public.portal_state (id, data, updated_by)
values ('indane-main', '{}'::jsonb, 'setup')
on conflict (id) do nothing;

alter table public.portal_state enable row level security;
alter table public.portal_audit_log enable row level security;

drop policy if exists "indane portal state read" on public.portal_state;
drop policy if exists "indane portal state insert" on public.portal_state;
drop policy if exists "indane portal state update" on public.portal_state;
drop policy if exists "indane audit read" on public.portal_audit_log;
drop policy if exists "indane audit insert" on public.portal_audit_log;

create policy "indane portal state read"
on public.portal_state
for select
to anon
using (id = 'indane-main');

create policy "indane portal state insert"
on public.portal_state
for insert
to anon
with check (id = 'indane-main');

create policy "indane portal state update"
on public.portal_state
for update
to anon
using (id = 'indane-main')
with check (id = 'indane-main');

create policy "indane audit read"
on public.portal_audit_log
for select
to anon
using (true);

create policy "indane audit insert"
on public.portal_audit_log
for insert
to anon
with check (true);

grant usage on schema public to anon;
grant select, insert, update on public.portal_state to anon;
grant select, insert on public.portal_audit_log to anon;
grant usage, select on sequence public.portal_audit_log_id_seq to anon;
